dev-server:
  deps:
    - hex-list.js
  exec: live-server

deploy:
  deps:
  - site/index.html
  - site/styles.css
  - site/script.js
  - site/model.js
  - site/chart.js
  - site/view.js
  - site/regioncode2state.js
  - site/hex-list.js
  - site-js

deploy-server:
  deps:
  - deploy
  exec: cd site && live-server

site/script.js:
  deps:
  - site
  - webcode/script.js
  exec: cp webcode/script.js site

site/model.js:
  deps:
  - site
  - webcode/model.js
  exec: cp webcode/model.js site

site/chart.js:
  deps:
  - site
  - webcode/chart.js
  exec: cp webcode/chart.js site

site/view.js:
  deps:
  - site
  - webcode/view.js
  exec: cp webcode/view.js site

site/regioncode2state.js:
  deps:
  - site
  - webcode/regioncode2state.js
  exec: cp webcode/regioncode2state.js site

site/hex-list.js:
  deps:
  - site
  - webcode/hex-list.js
  exec: cp webcode/hex-list.js site

site/styles.css:
  deps:
  - site
  - styles.css
  exec: cp styles.css site

site/index.html:
  deps:
  - site
  - index.html
  exec: cp index.html site

site-js:
  deps:
  - js
  exec: |
    cp webcode/hexes.js webcode/states.js site/
    touch $@

update-colors:
  exec: |
    node state-colors.js > states-new.js
    mv states-new.js webcode/states.js
    node to-yaml.js
    node from-yaml.js
    ava

site:
  exec: mkdir -p $@

test:
  deps:
    - standard
  exec: ava

hex-list-new.js:
  deps:
    - make-hex-list.js
  exec: . ./secrets.env && node $<  >$@

yaml:
  deps:
    - to-yaml.js
    - webcode/hexes.js
    - webcode/states.js
  exec: node $<  && touch $@

standard:
  deps:
    - js
    - webcode/script.js
    - webcode/model.js
  exec: standard --fix

js:
  deps:
    - from-yaml.js
    - data/hexes.yaml
    - data/states.yaml
  exec: node $< && touch $@
