dev-server:
  deps:
    - hex-list.js
  exec: live-server

deploy:
  deps:
  - site/index.html
  - site/styles.css
  - site/script.js
  - site/model.js
  - site/hex-list.js
  - site-js

deploy-server:
  deps:
  - deploy
  exec: cd site && live-server

site/script.js:
  deps:
  - site
  - script.js
  exec: cp script.js site

site/model.js:
  deps:
  - site
  - model.js
  exec: cp model.js site

site/hex-list.js:
  deps:
  - site
  - hex-list.js
  exec: cp hex-list.js site

site/styles.css:
  deps:
  - site
  - styles.css
  exec: cp styles.css site

site/index.html:
  deps:
  - site
  - index.html
  exec: cp index.html site

site-js:
  deps:
  - js
  exec: |
    cp hexes.js states.js site/
    touch $@

site:
  exec: mkdir -p $@

test:
  exec: node --test

hex-list-new.js:
  deps:
    - make-hex-list.js
  exec: . ./secrets.env && node $<  >$@

yaml:
  deps:
    - to-yaml.js
    - hexes.js
    - states.js
  exec: node $<  && touch $@

js:
  deps:
    - from-yaml.js
    - hexes.yaml
    - states.yaml
  exec: node $< && touch $@
