start:
  deps:
    - hex-list.js
  exec: live-server

test:
  exec: node --test

hex-list-new.js:
  deps:
    - make-hex-list.js
  exec: . ./secrets.env && node $<  >$@

hexes.js:
  deps:
  - make-data.js
  - hex-list.js
  exec: node  $<  >$@

yaml:
  deps:
    - to-yaml.js
    - hexes.js
    - states.js
  exec: node $<  && touch $@

js:
  deps:
    - from-yaml.js
    - hexes.yaml
    - states.yaml
  exec: node $< && touch $@
