dev-server:
  deps:
    - js
    - hex-list.js
  exec: cd site && live-server

update-colors:
  exec: |
    node state-colors.js > states-new.js
    mv states-new.js site/states.js
    node to-yaml.js
    node from-yaml.js
    ava

test:
  deps:
    - standard
  exec: ava

hex-list-new.js:
  deps:
    - make-hex-list.js
  exec: . ./secrets.env && node $<  >$@

yaml:
  deps:
    - to-yaml.js
    - site/hexes.js
    - site/states.js
  exec: node $<  && touch $@

standard:
  deps:
    - js
  exec: standard --fix

js:
  deps:
    - from-yaml.js
    - data/hexes.yaml
    - data/states.yaml
  exec: node $< && touch $@
