start:
  deps:
    - hex-list.js
  exec: live-server

hex-list-new.js:
  deps:
    - make-hex-list.js
  exec: . ./secrets.env && node $<  >$@

hexes.js:
  deps:
  - make-data.js
  - hex-list.js
  exec: node  $<  >$@
